# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: WebUI Deployment Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install npm dependencies
      working-directory: ./limpo-admin-webui
      run: npm install
    - name: Build the app
      working-directory: ./limpo-admin-webui
      run: sudo npm run build
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.LINUX_HOST}}
        key: ${{secrets.LINUX_PRIVATE_KEY}}
        username: ${{secrets.LINUX_USERNAME}}
        password: ${{secrets.LINUX_PASSWORD}}
        script: |
          echo "Conncected to Linux machine"
          echo "Deployment started"
          bash /home/jordan/cd-scripts/limpo-admin-webui.sh
    
   
